name: Laravel Backend CI

on:
  push:
    branches: [ "main", "new" ] # Trigger on pushes to these branches
  pull_request:
    branches: [ "main", "new" ] # Trigger on PRs to these branches

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, curl, libxml, mysql
        coverage: none

    - name: Install Dependencies
      working-directory: backend/src/laravel
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Prepare Environment
      working-directory: backend/src/laravel
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Run Migrations
      working-directory: backend/src/laravel
      run: php artisan migrate --force

    - name: Execute Tests
      working-directory: backend/src/laravel
      run: vendor/bin/phpunit
