name: Laravel Backend CI

on:
  push:
    branches: [ "main", "new" ]
  pull_request:
    branches: [ "main", "new" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, dom, curl, libxml, mysql
        coverage: none

    - name: Install Dependencies
      working-directory: backend/src/laravel
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Prepare Environment
      working-directory: backend/src/laravel
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Run Migrations
      working-directory: backend/src/laravel
      run: php artisan migrate --force

    - name: Execute Tests
      working-directory: backend/src/laravel
      run: vendor/bin/phpunit --stop-on-failure

  flutter-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/src

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze
      run: flutter analyze --no-fatal-infos --no-fatal-warnings

    - name: Test
      run: flutter test
